learning_log/urls.py
from django import contrib
from users import views
from django.conf.urls import url
from django.contrib import admin, auth
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    #homepage
    #path('', views.index, name='index'),
    path('', include('learning_logs.urls')),
    path('register/', views.register, name='register'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
"""Definiuje wzorce adresów URL dla learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
	#strona głowna.
	path('', views.index, name='index'),

	#wyświetlanie wszystkich tematow.
	path('topics/', views.topics, name = 'topics'),

	#Strona szczegółowa dotycząca pojedynczego tematu.
	path('topics/<int:topic_id>/', views.topic, name='topic'),

	#Strona przeznaczona do dodawania nowego tematu.
	path('new_topic/', views.new_topic, name='new_topic'),
	
	#Strona przeznaczona do dodawania nowego wpisu.
	path('new_entry/<int:topic_id>)/', views.new_entry, name ='new_entry'),

	#Strona przeznaczona do edycji wpisu
	path('edit_entry/<int:entry_id>/', views.edit_entry, name ='edit_entry'),
	
	#strona przeznaczona do usuwania wpisu
	path('topics/<int:entry_id>/remove_entry/', views.remove_entry, name='remove_entry'),

	#strona przeznaczona do usuwania tematu
	path('topics/<int:topic_id>/remove_topic/', views.remove_topic, name="remove_topic"),

	#strona przeznaczona do edycji tematu
	path('edit_topic/<int:topic_id>/', views.edit_topic, name="edit_topic"),
	
]

users/urls.py
"""Definiuje wzorce adresów URL dla aplikacji users."""

# from django import urls
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Dolaczanie domyślnych adresów URL uwierzytelniania
    path('', include('django.contrib.auth.urls')),

    # Strona rejestracji
    path('register/', views.register, name='register'),
    # strona edycji uzytkownika
    path('edit_settings/', views.edit_settings, name='edit_settings'),
    path('profile/<int:pk>/', views.profile, name= "profile"),
    path('profile/edit/<int:pk>', views.edit_profile, name='edit_profile'),
    path('profile/new_profile', views.new_profile, name= "new_profile"),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.


class Topic(models.Model):
    """Temat poznawany przez użytkownika."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    header_image = models.ImageField(blank=True, null=True, upload_to="images/")

    def __str__(self):
        """Zwraca reprezentację modelu w postaci ciągu tekstowego."""
        return self.text

    def delete(self):
        """ Usuwa zdjęcie tematu."""
        self.header_image.delete()
        super().delete()


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(blank=True, null=True, upload_to="images/profile/")
    website_url = models.CharField(max_length=255, blank=True, null=True)
    facebook_url = models.CharField(max_length=255, blank=True, null=True)
    twitter_url = models.CharField(max_length=255, blank=True, null=True)
    insta_url = models.CharField(max_length=255, blank=True, null=True)
    pinterest_url = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.user)

    def delete(self):
        """ Usuwa zdjęcie uzytkownika."""
        self.profile_pic.delete()
        super().delete()


class Entry(models.Model):
    """Konkretne informacje o postepie w nauce. """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    #text = models.TextField()
    text = RichTextField(blank = True, null = True)
    data_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Zwraca reprezentacje modelu w postaci ciągu tekstowego"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

learning_logs/forms.py
from django import forms

from .models import Topic, Entry, Profile


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'header_image']
        labels = {'text': '', "header_image": " Dodaj ikonę do tematu:"}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'': forms.Textarea(attrs={'cols': 80})}


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic', 'website_url', 'facebook_url', 'twitter_url', 'insta_url', 'pinterest_url']

learning_logs/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def check_topic_owner(request, topic_id):
    # upewniamy sie czy temat należy do bieżącego użytkownika
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404


# Utwórz swoje widoki
def index(request):
    """Strona główna dla aplikacji Learning Log."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Wyświetlanie wszystkich tematów."""
    topics = Topic.objects.order_by('date_added')
    # wyświetla tylko tematy dla zalogowanego użytkownika
    # topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Wyświetla pojedynczy temat i wszystkie powiązane z nim wpisy"""
    topic = get_object_or_404(Topic, id=topic_id)

    entries = topic.entry_set.order_by('-data_added')
    context = {'topic' : topic, 'entries' : entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Dodaj nowy temat"""
    if request.method != 'POST' :
        # nie przekazano żadnych danych, należy utworzyć pusty formularz
        form = TopicForm()
    else:
        # przekazano dane za pomocą zadania POST, należy je przetworzyć
        form = TopicForm(request.POST, request.FILES)

        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # return redirect('learning_logs:topics')
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    # Wyświetlanie pustego formularza
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Dodaj nowego wpisu dla określonego tematu."""
    topic = get_object_or_404(Topic, id=topic_id)

    check_topic_owner(request, topic.id)

    if request.method != 'POST' :
        # Nie przekazano żadnych danych, należy utworzyć pusty formularz
        form = EntryForm()
    else:
        # przekazano dane za pomocą zadania POST, należy je przetworzyć
        form = EntryForm(data = request.POST)

        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            # return redirect('learning_logs:topic', topic_id=topic_id)
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic_id]))

    # wyświetlanie pustego formularza
    context = { 'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edycja istniejącego wpisu"""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST' :
        # zadanie początkowe, wypełnienie formularza aktualna trescia wpisu
        form = EntryForm(instance = entry)
    else:
        # przekazano dane za pomocą zadania POST, należy je przetworzyć
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            # return redirect('learning_logs:topic', topic_id = topic.id)
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic.id]))

    context = {'entry' : entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def edit_topic(request, topic_id):
    """Edycja istniejącego tematu"""
    topic = Topic.objects.get(id=topic_id)

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST' :
        # zadanie początkowe, wypełnienie formularza aktualna trescia wpisu
        form = TopicForm(instance = topic)
    else:
        # przekazano dane za pomocą zadania POST, należy je przetworzyć
        form = TopicForm(data = request.POST, files = request.FILES, instance = topic)

        # usuniecie obrazka z serwera jeżeli nastepuje zmiana lub usuniecie obrazka
        if request.FILES.get('files') != topic.header_image:
            topic.delete()
        else:
            form = TopicForm(data = request.POST, files = request.FILES, instance = topic)
        
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.save()
            # return redirect('learning_logs:topic', topic_id = topic.id)
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic.id]))

    context = { 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)


@login_required
def remove_entry(request, entry_id):
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST' :
        # zadanie początkowe, wypełnienie formularza aktualna trescia wpisu
        form = EntryForm(instance=entry)
    else:
        # przekazano dane za pomocą zadania POST, należy je przetworzyć
        form = EntryForm(instance=entry)
        entry.delete()
        # return redirect('learning_logs:topic', topic_id = topic.id)
        return HttpResponseRedirect(reverse('learning_logs:topic',
                                    args=[topic.id]))

    context = {'entry' : entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/remove_entry.html', context)


@login_required
def remove_topic(request, topic_id):

    topic = Topic.objects.get(id = topic_id)

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST' :
        # zadanie początkowe, wypełnienie formularza aktualna trescia wpisu
        form = TopicForm(instance=topic)
    else:
        # przekazano dane za pomocą zadania POST, należy je przetworzyć
        form = TopicForm(instance=topic)
        topic.delete()
        # return redirect('learning_logs:topic', topic_id = topic.id)
        return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/remove_topic.html', context)

learning_logs/templates/learning_logs/baseOLD.html
<p>
    <a href = "{% url 'learning_logs:index' %}" > &ensp; Learning Log</a>
    <a href = "{% url 'learning_logs:topics' %}" > &ensp; Tematy </a>
    {% if user.is_authenticated %}
        Witaj, {{ user.username }}
        <a href=" {% url 'users:logout' %}"> &ensp; Wyloguj </a>
    {% else %}
        <a href="{% url 'users:register' %}">  &ensp; Rejestruj  </a> -
        <a href="{% url 'users:login' %}">  &ensp; Zaloguj  </a>
    {% endif %} 
</p>

{% block content %} {% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
  <h2 style="text-align:center;">
    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
  </h2>
{% endblock page_header %}
{% block content %}
  {{ form.media }}
  <br>
  <h3 style="text-align:center;">Edytuj wpis:</h3>
  <br>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form" 
    enctype= "multipart/form-data" align="center">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name='submit' class="btn btn-primary">Zapisz zmiany</button>
    <input class="btn btn-primary" type=button value="Wróć" onClick="javascript:history.go(-1);">
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}
  <h3 style="text-align:center;">Edytuj temat:</h3>
  <form action="{% url 'learning_logs:edit_topic' topic.id %}" method='post' enctype= "multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name='submit' class="btn btn-primary">Zapisz zmiany</button>
    <input class="btn btn-primary" type=button value="Wróć" onClick="javascript:history.go(-1);">
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}


{% block page_header %}
    <div class ="jumbotron">
    <h1 class="display-3"> Monitoruj postępy w nauce</h1>

    <p class="lead"> Załóż konto, aby rozpocząć korzystanie z aplikacji
        Learning Log oraz wyświetlić listę poznawanych tematów. Gdy
        nauczysz się czegoś nowego na dany temat, utwórz wpis
        podsumowujący to, czego się nauczyłeś.</p>

    <a class ="btn btn-lg btn-primary" href=" {% url 'users:register' %}" 
role="button">Zarejestruj konto &raquo;</a>
    </div>
    
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h2 style="text-align:center;">
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h2>
{% endblock page_header %}
{% block content %}
  {{ form.media }}
  <h3 style="text-align:center;">Dodaj nowy wpis:</h3>
  <br>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form" 
    enctype= "multipart/form-data" align="center">
    {% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button name='submit' class="btn btn-primary">Dodaj wpis</button>
  <input class="btn btn-primary" type=button value="Wróć" onClick="javascript:history.go(-1);">
	{% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_entryOLD.html
{% extends "learning_logs/base.html" %} 

{% block content %} 
    <p><a href="{% url 'learning_logs:topic' topic.id %}" > {{ topic }} </a></p>

    <p>Dodaj nowy wpis:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' >
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Dodaj wpis</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %} 
{% load bootstrap4 %}

{% block content %}
<h3 style="text-align:center;">Dodaj nowy temat: </h3>
  <form action="{% url 'learning_logs:new_topic' %}" method='post' enctype= "multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div>
    <br>
      {% buttons %}
      <button name='submit' class="btn btn-primary">Dodaj temat</button>
      <input class="btn btn-primary" type=button value="Wróć" onClick="javascript:history.go(-1);">
      {% endbuttons %}
    </div>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topicOLD.html
{% extends "learning_logs/base.html" %} 

{% block content %} 
    <p> Dodaj nowy temat: </p>

    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %} 
        {{ form.as_p }}
        <button name="submit">Dodaj temat</button>
    </form>

{% endblock content %} 

learning_logs/templates/learning_logs/remove_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block header %}
  <h2>
    Usuń wpis
  </h2>
{% endblock header %}

{% block content %}
  <h3>Czy na pewno chcesz usunąć wpis: </h3>
  <form action="{% url 'learning_logs:remove_entry' entry.id %}" method='post'>
    {% csrf_token %}
    <div class ="jumbotron">
    <p class="lead"> {{ entry|safe }} </p>
    </div>
    {% buttons %}
    <button name='submit' class="btn btn-primary">Usuń</button>
    <input class="btn btn-primary" type=button value="Wróć" onClick="javascript:history.go(-1);">
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/remove_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block header %}
  <h2>
    Usuń temat
  </h2>
{% endblock header %}

{% block content %}
  <h3>Czy na pewno chcesz usunąć temat: </h3>
  <form action="{% url 'learning_logs:remove_topic' topic.id %}" method='post'>
    {% csrf_token %}
    <div class ="jumbotron">
    <p class="lead"> {{ topic }} </p>
    </div>
    {% buttons %}
    <button name='submit' class="btn btn-primary">Usuń</button>
    <input class="btn btn-primary" type=button value="Wróć" onClick="javascript:history.go(-1);">
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h2 style="text-align:center;"> {{ topic }} 
    <small><a href= {% url 'learning_logs:edit_topic' topic.id %} >[Edytuj]</small>
    <small><a href= {% url 'learning_logs:remove_topic' topic.id %} >[Usuń]</small>
    </h2>
{% endblock page_header %}

{% block content %}
    <h3><p style="text-align:center;">
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Dodaj nowy wpis</a>
    </p></h3>


    {% for entry in entries %}
        <div class="card bg-light mb-3">
            <h5 class="card-header" align="center">
                <p class="card-text">Opublikowany {{ entry.data_added|date:'d M Y H:i' }} przez {{ topic.owner }}
                    <small><a href=" {% url 'learning_logs:edit_entry' entry.id %}">[Edytuj wpis]</a></small>
                    <small><a href=" {% url 'learning_logs:remove_entry' entry.id %}">[Usuń wpis]</a></small>
                </p>
            </h5>
                <div class="card-body">
                    {{ entry.text|safe }}
                </div>
        </div>
    {% empty %}
        Nie ma jeszcze żadnego wpisu dla tego tematu.
    {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topicOLD.html
{% extends 'learning_logs/base.html' %} 

{% block content %} 

    <p> Temat: {{ topic}} </p>

    <p> Wpisy:</p>
    <p> 
        <a href="{% url 'learning_logs:new_entry' topic.id %}" > Dodaj nowy wpis </a>
    </p>

    <ul>
    {% for entry in entries %} 
        <li>
            <p>{{ entry.data_added|date:'d M Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p> 
                <a href ="{% url 'learning_logs:edit_entry' entry.id %}" > Edytuj wpis </a>
            </p> 
        </li>
    {% empty %} 
        <li> Nie ma jeszcze żadnego wpisu. </li>
    {% endfor %} 
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% load static %}
{% block page_header %}
    <h1 style="text-align:center;"> Tematy </h1>
{% endblock page_header %}

{% block content %}

<h3 style="text-align:center"><a href =" {% url 'learning_logs:new_topic' %}" > Dodaj nowy temat</a></h3>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
            {% for topic in topics %}
                <div class="col">
                    <div class="card shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225">
                            <defs>
                                <clipPath id="rectView">
                                <rect width="100%" height="100%" fill="#55595c"></rect></clipPath>
                            </defs>
                            {% if topic.header_image %}
                                <image width ="100%" height="225" xlink:href="{{ topic.header_image.url }}" clip-path="url(#rectView)" >
                            {% else %}
                                <image width ="100%" height="225" xlink:href="{% static 'theblog\images\default.png' %}" clip-path="url(#rectView)" >
                            {% endif %}
                            
                        </svg>
                        <div class="card-body">
                            <p class="card-text" style="text-align:center"> {{ topic }} </p>
                            <div class="d-flex justify-content-center">
                                <div class="btn-group">
                                    <small><button type="button" class="btn btn-sm btn-outline-secondary" 
                                        onclick="location.href='{% url 'learning_logs:topic' topic.id %}'">
                                        Pokaż więcej
                                    </button></small>
                                    <small><button type="button" class="btn btn-sm btn-outline-secondary" 
                                        onclick="location.href='{% url 'learning_logs:edit_topic' topic.id %}'">
                                        Edytuj
                                    </button></small>
                                    <small><button type="button" class="btn btn-sm btn-outline-secondary" 
                                        onclick="location.href='{% url 'learning_logs:remove_topic' topic.id %}'">
                                        Usuń
                                    </button></small>
                                </div> 
                            </div>
                        </div>
                    </div>
                </br>
                </div>
                
            {% empty %} 
                <h3> Nie został jeszcze dodany żaden temat.</h3>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock content %}

learning_logs/templates/learning_logs/topicsOLD.html
{% extends "learning_logs/base.html" %}

{% block content %} 
    <p> Tematy </p>

    <ul>
        {% for topic in topics %} 
            <li> 
                <a href=" {% url 'learning_logs:topic' topic.id %}" > {{topic}} </a>
            </li> 
        {% empty %} 
            <li> Nie został dodany jeszcze żaden temat. </li>
        {% endfor %} 
    </ul>

    <a href=" {% url 'learning_logs:new_topic' %}" > Dodaj nowy temat </a>

{% endblock content %} 